name: Radio Show System
slug: radio-show-system
description: Pre and post tasks associated with a given show
category: radio-show-systems
tags:
  - review
  - planning
  - productivity
  - weekly
estimated_duration: 45m
recurrence_suggestion: weekly
version: 1.0.0
author: Colin Gourlay
