name: Radio Show System
slug: radio-show-system
description: End-to-end workflow for preparing, delivering and publishing a radio show
category: creative
tags:
  - radio
  - media
  - broadcast
  - repeatable
estimated_duration: 3h
recurrence_suggestion: weekly
version: 1.0.0
author: Colin Gourlay
