name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-test:
    name: build-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: echo "Build goes here"

      - name: Test
        run: echo "Tests go here"